services:
  - type: web
    name: bitly-clone
    env: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_DIALECT
        value: org.hibernate.dialect.H2Dialect
      - key: DATABASE_DRIVER
        value: org.h2.Driver
      - key: JWT_SECRET
        value: f+hnWqKeSnU0fKcdqA5soOjTt0zBhfOQjZFnkEDy7FM=
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: FRONTEND_URL
        value: https://bitly-clone-backend-6d3c.onrender.com
